### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by ddevault** [prometheus-community/smartctl_exporter#10]
Please use go modules for this project. It should be straightforward:

    go mod init github..com/Sheridan/smartctl_exporter

Then do a quick go build to populate go.mod and go.sum and check them in.

Thanks!

**Comment by SuperQ** [comment]
Looks like there's a Go mod file now. But the release aren't tagged with semver like `v0.6.0`.

**Comment by SuperQ** [comment]
This is now done.
