### ISSUE TITLE
does not compile with golang 1.19.7

### ISSUE THREAD

**Issue by matthewdarwin** [prometheus-community/smartctl_exporter#114]
smartctl_exporter does not compile with golang 1.19.7

background: https://github.com/go-critic/go-critic/issues/1019

```
/tmp/build.1681264729.245577/build/bin/golangci-lint run  ./...
readjson.go:18:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
        ^
make: *** [Makefile.common:171: common-lint] Error 1
```

**Comment by frittentheke** [comment]
@matthewdarwin  was this issue not fixed via https://github.com/prometheus-community/smartctl_exporter/pull/115 ?

**Comment by matthewdarwin** [comment]
I don't know if it was or not, but the problem doesn't exist anymore using golang 1.20.7 on version 0.10.0

(i had worked around the problem by using golang 1.18.x)
