### ISSUE TITLE
metrics do not include grown defects

### ISSUE THREAD

**Issue by jeffmontagna** [prometheus-community/smartctl_exporter#118]
The json output of `smartctl` includes `scsi_grown_defect_list` which correlates to `Elements in grown defect list` of the text output.  This value is not included in the metrics, would it be possible to add `scsi_grown_defect_list` to the metrics?

- `scsi_grown_defect_list` is available when the device type is `scsi`
- The value of `Elements in grown defect list` in the text output is  `scsi_grown_defect_list` divided by 8.

- Example from a SAS disk with defects:
```
root@anode1:~/temp# smartctl /dev/sdc -a -j | jq .scsi_grown_defect_list
240
root@anode1:~/temp# smartctl /dev/sdc -a -j | jq .device
{
  "name": "/dev/sdc",
  "info_name": "/dev/sdc",
  "type": "scsi",
  "protocol": "SCSI"
}
```
- Text output
```
root@anode1:~/temp# smartctl /dev/sdc -a | grep 'grown defect'
Elements in grown defect list: 30
```

- Example from a SATA attached SSD
```
root@anode1:~/temp# smartctl /dev/sda -a -j | jq .scsi_grown_defect_list
null
```

**Comment by robbat2** [comment]
This was already implemented in v0.10.0, and I confirm it works on SAS disks.

**Comment by k0ste** [comment]
Added in #131

**Comment by NiceGuyIT** [comment]
#131 was merged. Closing.
