### ISSUE TITLE
Add build for aarch64 architecture

### ISSUE THREAD

**Issue by varac** [prometheus-community/smartctl_exporter#119]
Please add a aarch64 build for upcoming releases, so SBC boards like [Rockpro64](https://www.pine64.org/rockpro64/) are supported. Thanks !

**Comment by enmanuelmoreira** [comment]
That would be great! Thinking about arm64 ampere processors and raspberry pi 4-5 devices

**Comment by alex-dna-tech** [comment]
Duplicate of #105
