### ISSUE TITLE
Do not exit if no devices are found

### ISSUE THREAD

**Issue by Knalltuete5000** [prometheus-community/smartctl_exporter#128]
The smartctl exporter can be configured in multiple way either by configuring a list of devices or let the exporter find the devices. If the second case is used the exporter exits if no devices are found (see https://github.com/prometheus-community/smartctl_exporter/blob/895bf1eeb3487b118ff4aa2de94aac21f0e146fa/main.go#L128).

This can be problematic if the exporter is deployed in a virtual environment where no devices can be found by smartctl. The exporter instantly crashes and prometheus is not able to scrap the target.

It would be useful to include a metric that indicates how many devices were successfully analyzed during a run so the exporter can also be deployed in a virtual environment where smartctl does not detect any devices.

In addition such a metric can be useful if a static list of devices is configured to be able to check if all devices are recognized and the the smartctl data is read from.

**Comment by Knalltuete5000** [comment]
You are right: Why deploy the exporter when there are no devices?
In my opinion there are reasons to deploy this exporter in such a scenario/environment. Let me explain

1. You might have a production and a development setup. In some cases the development system is virtualized but you want to have as far as possible the same deployment methods as for production system. And such an exporter should not make a deployment more complicated.
2. It is not yet implemented, but as @frittentheke suggested in #130, it would be useful to scan for devices in a regular interval for new and missing/disappearing devices. Therefor the exporter must start even if no devices are found.

I hope this cases clarify the motivation behind the issue and the PR

**Comment by frittentheke** [comment]
>     2. It is not yet implemented, but as @frittentheke suggested in [Newly added disks are not discovered until exporter is restarted #130](https://github.com/prometheus-community/smartctl_exporter/issues/130), it would be useful to scan for devices in a regular interval for new and missing/disappearing devices. Therefor the exporter must start even if no devices are found.

Even in physical servers only environments I imagine cases where servers are disk-less and booted over the network. Some of them might also carry local NVME disks to e.g. provide fast local storage to VMs or similar. In that case I simply want to have the exporter on all machines and get info on any disks that it can find.

So I might start of with none, then add two ... and weeks later I might add even more. Thus my issue to also add a periodic rescan.

**Comment by k0ste** [comment]
> So I might start of with none, then add two ... and weeks later I might add even more. Thus my issue to also add a periodic rescan.

You can use [systemd.timer](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) to achieve this

**Comment by frittentheke** [comment]
> > So I might start of with none, then add two ... and weeks later I might add even more. Thus my issue to also add a periodic rescan.
> 
> You can use [systemd.timer](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) to achieve this

That sounds more like a hack (in the sense that "it works, but is not really elegant").
But staying on this very issue, the exporter does not work with "none" disks yet and there is no reload. Restarting every few minutes with a timer seems a little harsh just to trigger a rescan for the list of devices....

**Comment by SuperQ** [comment]
You don't need a timer, systemd units can restart and have backoff controls.

This exporter only does dynamic scan on startup, not continuously, so the only way to pick up device changes is to trigger a restart anyway.

Right now it makes no sense to startup with zero devices configured.

**Comment by frittentheke** [comment]
> You don't need a timer, systemd units can restart and have backoff controls.
> This exporter only does dynamic scan on startup, not continuously, so the only way to pick up device changes is to trigger a restart anyway.

That's why I also opened https://github.com/prometheus-community/smartctl_exporter/issues/130

> Right now it makes no sense to startup with zero devices configured.

There is really not much more I could argue with. As said, I personally rather treat the fact that there are no devices with a metric telling me just that, than with the whole exporter not even starting. Refreshing the device list at runtime and is a different matter an was a little off-topic to this issue.

But if you really don't want the exporter to be able to keep running without devices or would accept the linked PR adding this, I'd say this issue should be closed / rejected.

**Comment by Knalltuete5000** [comment]
May I ask if the described scenarios are now valid usecases since a rescanning mechanism was introduced via #130/#140.
So the exporter can start without finding any devices and through the rescanning devices are discovered later

**Comment by NiceGuyIT** [comment]
> Right now it makes no sense to startup with zero devices configured.

This argument is void now that periodic scanning has been implemented.

IMHO monitoring for `up` indicates an error condition with the program or server, not the logic. Monitoring for `count(smartctl_device) > 0` or any other metric is a reflection of the logic, not the program or server. This separation of concerns took a large step forward with rescanning logic, and another step forward with the PR for this issue.

**Comment by k0ste** [comment]
With periodic scanning implemented, now we can alert, when `smartctl_exporter` find device, but can't get metrics for some reason, for example due `".message"` in JSON

```python
(sum by (instance) (smartctl_devices) - count by (instance) (smartctl_device)) > 0
```
