### ISSUE TITLE
Newly added disks are not discovered until exporter is restarted

### ISSUE THREAD

**Issue by frittentheke** [prometheus-community/smartctl_exporter#130]
Extending on https://github.com/prometheus-community/smartctl_exporter/issues/128, the exporter currently does not scan for devices after its initial startup - see https://github.com/prometheus-community/smartctl_exporter/blob/895bf1eeb3487b118ff4aa2de94aac21f0e146fa/main.go#L125.

I propose to add such functionality at least in the sense to scan for new devices periodically and add them to the list.
Also removing devices which are not present anymore might make sense, others might argue that this carries some information in itself.

But I believe the exporter should be able to run and always return data for the current list of devices installed in the system.

**Comment by k0ste** [comment]
Workaround that we use in prod #139

**Comment by frittentheke** [comment]
> Workaround that we use in prod #139

Thanks @k0ste  for helping with the issue and for cleaning up that systemd unit.


I am still wondering if a PR with (configurable) rescan interval to not having to restart the whole exporter would be accepted?
Maybe (:blush:) if an optional rescan is implemented this could also cover the use-case to not exist if there are no devices 
(https://github.com/prometheus-community/smartctl_exporter/issues/128)

^^ @SuperQ

**Comment by k0ste** [comment]
@frittentheke why not, if PR will be 😇
