### ISSUE TITLE
Duplicated device_status metric

### ISSUE THREAD

**Issue by tekert** [prometheus-community/smartctl_exporter#136]
Metrics:
`smartctl_device_status`
`smartctl_device_smart_status`

Both take values from json key:
`smart_status.passed`

Code blame:
`mineSmartStatus()`   from PR #16  description: Add NVMe metrics
`mineDeviceStatus(`)  from PR #14 description: Add a new metric smartctl_device_status for the SMART health status.

https://github.com/prometheus-community/smartctl_exporter/blame/master/smartctl.go#L326
https://github.com/prometheus-community/smartctl_exporter/blame/master/smartctl.go#L386

**Comment by tekert** [comment]
https://github.com/prometheus-community/smartctl_exporter/blame/master/smartctl.go#L386

**Comment by tekert** [comment]
I removed the ´smartctl_device_status´, ´smartctl_device_smart_status´ seems more descriptive, but this a problem now, 
leave it like this, repurpose the metric or delete one of them.

**Comment by NiceGuyIT** [comment]
Thanks @tekert! I agree. `smartctl_device_smart_status` is more inline with the JSON output from `smartctl`.
