### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by robbat2** [prometheus-community/smartctl_exporter#143]
Could you please publish a new formal release, to include in Linux distribution packaging? There have been more than 6 months of great improvements, like the device-filtering, SCSI metrics, fixing the SSD counters, device scanning & more.

**Comment by k0ste** [comment]
Fixed in #142

**Comment by NiceGuyIT** [comment]
Done! Have a great weekend.

[0.10.0 / 2023-06-10](https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.10.0)
