### ISSUE TITLE
smartctl_exporter should be cgroup aware

### ISSUE THREAD

**Issue by uhthomas** [prometheus-community/smartctl_exporter#201]
[Go is not cgroup aware](https://github.com/golang/go/issues/33803). This means the VictoriaMetrics operator will be throttled hard in containerised environments with CPU limits.

The below screenshot shows the container with a CPU limit in Kubernetes. The first half of the time series is on a 13600k, with 20 threads. The second half is when the machine changed to use an EPYC 7763 with 128 threads. I changed the CPU limit for the third deployment, which is why it looks a bit more normal again.

![image](https://github.com/prometheus-community/smartctl_exporter/assets/9749173/a67405c8-8cea-4c9d-84b5-f767a041c372)

[automaxprocs](https://github.com/uber-go/automaxprocs) can use cgroups automatically.

**Comment by SuperQ** [comment]
It would likely be simpler to deploy with a simple `GOMAXPROCS=1`. The exporter uses very little CPU itself.

**Comment by lahwaacz** [comment]
@SuperQ Can this be done as-is or does it need something similar to https://github.com/prometheus/node_exporter/pull/2530?
