### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by NiceGuyIT** [prometheus-community/smartctl_exporter#213]
I noticed GitHub Discussions is not enabled. Should this be enabled to allow people to ask questions, ask for troubleshooting assistance or discuss new features or changes?

Looking at other exporter repos, only [monaco-promql][1] has GitHub Discussions enabled. The [Prometheus Community][2] site has this to say:
> For questions and discussions, many repositories offer GitHub discussions. Generally, the other community channels listed here are best suited to get support or discuss overarching topics.

Vote with :+1: or :-1: 

[1]: https://github.com/prometheus-community/monaco-promql
[2]: https://prometheus.io/community/

**Comment by SuperQ** [comment]
Yes, we've been enabling discussions across Prometheus projects. We've mostly left it up to the maintainers of the repos to decide if they want it on or not.
