### ISSUE TITLE
Collect additional metrics

### ISSUE THREAD

**Issue by Lusitaniae** [prometheus-community/smartctl_exporter#222]
This could possibly be used to estimate leftover capacity against DWPD of known drives?

```
Data Units Read:                    705,333 [361 GB]
Data Units Written:                 4,237,453 [2.16 TB]
```

Or is it redundant to the spare capacity metrics like `smartctl_device_available_spare`?

**Comment by k0ste** [comment]
You can do it simpler, use 'spare' metric or 'percentage' metric

```
smartctl_device_available_spare < smartctl_device_available_spare_threshold or smartctl_device_percentage_used > 100
```
