### ISSUE TITLE
Configuration via flags only

### ISSUE THREAD

**Issue by baryluk** [prometheus-community/smartctl_exporter#30]
I really like ability to run exporters, and other servers, with no extra files and configs, by specifying everything on command line:

`./smartctl_exporter --port=9633 "--devices=/dev/sd*"`

Is really all one needs, with rest using defaults, but overridable using flags too (i.e. for testing).

It makes it easier to deploy, manage, and monitor itself.

Regards,
Witold

**Comment by k0ste** [comment]
Seems this in #68
