### ISSUE TITLE
i get some errors.

### ISSUE THREAD

**Issue by a472938887** [prometheus-community/smartctl_exporter#38]
![image](https://user-images.githubusercontent.com/42056433/161685623-8381fe25-6052-4d9f-8023-2ca084192389.png)

**Comment by kotloki** [comment]
I have same trouble. Did you manage ti find any solution?

**Comment by kotloki** [comment]
It may be resolve, when you change collect_not_more_than_period to 0s.
It§s not good idea, but it works.

See https://github.com/prometheus-community/smartctl_exporter/issues/19

**Comment by lahwaacz** [comment]
The errors  `Too early to collect for device /dev/sda` and `panic: runtime error: index out of range` were addressed in #18 and #81 so this can be closed.
