### ISSUE TITLE
How to automatically collect all the hard disks of a server

### ISSUE THREAD

**Issue by a472938887** [prometheus-community/smartctl_exporter#52]
Consistent with the title，I have many servers. Some servers have different hard disks，maybe 37，maybe 61，maybe 13.

**Comment by lahwaacz** [comment]
If you don't specify any `devices` in the config, they are scanned using the `smartctl --scan-open` command.

**Comment by a472938887** [comment]
> 

thanks! i will try it!

**Comment by a472938887** [comment]
> If you don't specify any `devices` in the config, they are scanned using the `smartctl --scan-open` command.

thanks! i'll try it !

**Comment by a472938887** [comment]
> If you don't specify any in the config, they are scanned using the command.`devices``smartctl --scan-open`

He suggested:
flag provided but not defined: -scan-open
Usage of ./smartctl_exporter:
  -config string
        Path to smartctl_exporter config file (default "/etc/smartctl_exporter.yaml")
  -debug
        Debug log output
  -verbose
        Verbose log output
  -version
        Show application version and exit
