### ISSUE TITLE
Suggest : support configure filtering metrics and attribute_id

### ISSUE THREAD

**Issue by ChaoHsupin** [prometheus-community/smartctl_exporter#57]
Hope to provide a optional configuration , that not collected in `/metrics` about user not attention, and a label `attribute_id` under `smartctl_device_attribute`.This effectively reduces the bandwidth occupation during the pometheus scrape process.

configure example(All metrics will be collected by default):
````
metrics_allow_list:
 - smartctl_device
 - smartctl_device_attribute
smart_attribute_id_allow_list:
 - 148

**Comment by anthonyeleven** [comment]
IMHO the bandwidth for scraping these metrics is trival.  Common Prometheus practice is to drop undesired metrics during Prom-side ingest.

```# curl http://10.x.x.x:9633/metrics | wc -m
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  103k    0  103k    0     0  7017k      0 --:--:-- --:--:-- --:--:-- 7395k```

**Comment by ChaoHsupin** [comment]
@anthonyeleven 
Thanks for your reply ! 
When the number of machines is large, it is important to save bandwidth and reduce the load of Prometheus. I can add this configer to our internal image.

**Comment by anthonyeleven** [comment]
As text files, I really couldn't see Prom exposition files being significant from a bandwidth perspective.  As for reducing load I don't have enough experience to know, but I've personally never had ingest load be an issue. ymmv. Centralized filtering is easier to manage fwiw.
