### ISSUE TITLE
quay image

### ISSUE THREAD

**Issue by kfox1111** [prometheus-community/smartctl_exporter#59]
We need to get an image onto quay so the helm chart can work with it out of the box. I was under the impression there was one, but I'm not seeing it yet.

**Comment by kfox1111** [comment]
Related to: https://github.com/prometheus-community/helm-charts/pull/2357

**Comment by monotek** [comment]
Imho it was available here: https://quay.io/organization/prometheus at least we should have had a successful GitHub action run with that image.

Or ist this the right repo?

https://hub.docker.com/r/prometheuscommunity/smartctl-exporter

**Comment by kfox1111** [comment]
the one here: https://hub.docker.com/r/prometheuscommunity/smartctl-exporter/tags still has the missing smartctl binary issue. :(

Can we get a new build please? would need to be tagged 0.7.1.

**Comment by onedr0p** [comment]
@SuperQ any chance we can see some effort on getting this fixed?

```
docker pull quay.io/prometheus/smartctl-exporter:v0.7.0

Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Comment by kfox1111** [comment]
+1

in the mean time, you can use: pnnlmiscscripts/smartctl-exporter:0.7-2

**Comment by SuperQ** [comment]
Prometheus Community exporters are under a [different image repo](https://quay.io/organization/prometheuscommunity).

```
docker pull quay.io/prometheuscommunity/smartctl-exporter:v0.7.0
```

**Comment by onedr0p** [comment]
@SuperQ 

```
❯ docker pull quay.io/prometheuscommunity/smartctl-exporter:v0.7.0
Error response from daemon: unauthorized: access to the requested resource is not authorized
```
