### ISSUE TITLE
v0.7 : version mismatch

### ISSUE THREAD

**Issue by Daryes** [prometheus-community/smartctl_exporter#66]
Hello,
Nothing serious, just the `--version` returning a wrong value with the latest release :
```
$ ./smartctl_exporter-0.7.0.linux-amd64/smartctl_exporter --version
smartctl_exporter version: 0.5
```
Should be 0.7.0

Thanks

**Comment by SuperQ** [comment]
Yes, I have a PR in progress to rework the startup code to source this information correctly.
