### ISSUE TITLE
Ability to exclude device from smartctl scan

### ISSUE THREAD

**Issue by k3nny0ne** [prometheus-community/smartctl_exporter#97]
I want do exclude some specific devices from metrics collection (like, NVMe).
It would be cool to specify them in command line (e.g. `--smartctl.exclude /dev/nvme1 --smartctl.exclude /dev/nvme2 ...`).

**Comment by SuperQ** [comment]
Seems like a reasonable idea. PRs welcome. There's an example [device filter pattern](https://github.com/prometheus/node_exporter/blob/fd14fb04c7208b440319ab3e048985f870994dc3/collector/device_filter.go) in the node_exporter that can be used here.

**Comment by k0ste** [comment]
This is the same was #72

**Comment by SuperQ** [comment]
@k0ste I think this is similar, but not exactly the same.
